/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form4;

import form4.Form4.KhoiA;
import form4.Form4.KhoiC;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 * 
 */
public class QLTS extends javax.swing.JFrame {
    ArrayList<KhoiA> dska = new ArrayList<>();
    ArrayList<KhoiC> dskc = new ArrayList<>();
    /**
     * Creates new form QLTS
     */
    
    public QLTS() {
        initComponents();
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lb_hoTen = new javax.swing.JLabel();
        hoTen = new javax.swing.JTextField();
        lb_ngaySinh = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JTextField();
        lb_diaChi = new javax.swing.JLabel();
        diaChi = new javax.swing.JTextField();
        lb_khoi = new javax.swing.JLabel();
        lb_diemToan = new javax.swing.JLabel();
        lb_diemLy = new javax.swing.JLabel();
        lb_diemHoa = new javax.swing.JLabel();
        diemToan = new javax.swing.JTextField();
        diemLy = new javax.swing.JTextField();
        diemHoa = new javax.swing.JTextField();
        lb_diemVan = new javax.swing.JLabel();
        lb_diemSu = new javax.swing.JLabel();
        lb_diemDia = new javax.swing.JLabel();
        diemVan = new javax.swing.JTextField();
        diemSu = new javax.swing.JTextField();
        diemDia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        khoiA = new javax.swing.JRadioButton();
        khoiC = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lí Thí Sinh");

        lb_hoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_hoTen.setText("Ho Ten");

        lb_ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ngaySinh.setText("Ngay Sinh");

        lb_diaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diaChi.setText("Dia Chi");

        lb_khoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_khoi.setText("Khoi");

        lb_diemToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemToan.setText("Diem toan");

        lb_diemLy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemLy.setText("Diem ly");

        lb_diemHoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemHoa.setText("Diem hoa");

        diemToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemToanActionPerformed(evt);
            }
        });

        lb_diemVan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemVan.setText("Diem van");

        lb_diemSu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemSu.setText("Diem su");

        lb_diemDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_diemDia.setText("Diem dia");

        diemSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemSuActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        khoiA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        khoiA.setText("Khoi A");
        khoiA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khoiAActionPerformed(evt);
            }
        });

        khoiC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        khoiC.setText("Khoi C");
        khoiC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khoiCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ngaySinh)
                    .addComponent(lb_diaChi)
                    .addComponent(lb_khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_diemToan)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_diemSu)
                            .addComponent(lb_diemVan)
                            .addComponent(lb_diemDia)
                            .addComponent(btnThem)
                            .addComponent(lb_diemHoa)
                            .addComponent(lb_diemLy))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addComponent(jLabel1)
                    .addComponent(hoTen)
                    .addComponent(ngaySinh)
                    .addComponent(diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(diemToan)
                    .addComponent(diemLy)
                    .addComponent(diemHoa)
                    .addComponent(diemVan)
                    .addComponent(diemSu)
                    .addComponent(diemDia)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(khoiA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(khoiC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_hoTen)
                    .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ngaySinh)
                    .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diaChi)
                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_khoi)
                    .addComponent(khoiA)
                    .addComponent(khoiC))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diemToan)
                    .addComponent(diemToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_diemLy)
                    .addComponent(diemLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diemHoa)
                    .addComponent(diemHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diemVan)
                    .addComponent(diemVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diemSu)
                    .addComponent(diemSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_diemDia)
                    .addComponent(diemDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnReset)
                    .addComponent(btnThoat))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diemToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemToanActionPerformed

    private void diemSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemSuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemSuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        hoTen.setText("");
        ngaySinh.setText("");
        diaChi.setText("");
        khoiA.setSelected(false);
        khoiC.setSelected(false);
        diemToan.setText("");
        diemLy.setText("");
        diemHoa.setText("");
        diemVan.setText("");
        diemSu.setText("");
        diemDia.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed
    public boolean KiemTraRongA()
    {
        if (hoTen.getText().equals("")||ngaySinh.getText().equals("")||diaChi.getText().equals("")||diemToan.getText().equals("")||diemLy.getText().equals("")||diemHoa.getText().equals("")|| !khoiA.isSelected()){
            return true;
        }
        return false;
    }
    public boolean KiemTraRongC()
    {
        if (hoTen.getText().equals("")||ngaySinh.getText().equals("")||diaChi.getText().equals("")||diemVan.getText().equals("")||diemSu.getText().equals("")||diemDia.getText().equals("")|| !khoiC.isSelected()){
            return true;
        }
        return false;
    }   
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(khoiA.isSelected()){
            if(KiemTraRongA() == false){
                KhoiA ka = new KhoiA();
                ka.setHoTen(hoTen.getText());
                ka.setNgaySinh(ngaySinh.getText());
                ka.setDiaChi(diaChi.getText());
                ka.setDiemToan(Float.parseFloat(diemToan.getText()));
                ka.setDiemLy(Float.parseFloat(diemLy.getText()));
                ka.setDiemHoa(Float.parseFloat(diemHoa.getText()));
                dska.add(ka);   
                if((ka.getDiemToan() + ka.getDiemHoa() + ka.getDiemLy()) > 20){          
                      System.out.println("Thi sinh diem > 20: " + ka.toString());
                }
                
                    JOptionPane.showMessageDialog(this,"Thêm thành công");
                    }else{
                        JOptionPane.showMessageDialog(this,"Các trường không được rỗng","Error",JOptionPane.ERROR_MESSAGE);
                    }
            }
        else if(khoiC.isSelected()){
                if(KiemTraRongC() == false){
                    KhoiC kc = new KhoiC();
                    kc.setHoTen(hoTen.getText());
                    kc.setNgaySinh(ngaySinh.getText());
                    kc.setDiaChi(diaChi.getText());
                    kc.setDiemVan(Float.parseFloat(diemVan.getText()));
                    kc.setDiemSu(Float.parseFloat(diemSu.getText()));
                    kc.setDiemDia(Float.parseFloat(diemDia.getText()));
                    dskc.add(kc);
                    if((kc.getDiemVan() + kc.getDiemSu() + kc.getDiemDia()) > 20){
                            System.out.println("Thi sinh diem > 20: " + kc.toString());
                       }
                        
                    JOptionPane.showMessageDialog(this,"Thêm thành công");
                    }else{
                        JOptionPane.showMessageDialog(this,"Các trường không được rỗng","Error",JOptionPane.ERROR_MESSAGE);
                    }
        }
    }//GEN-LAST:event_btnThemActionPerformed
    
    private void khoiAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khoiAActionPerformed
        // TODO add your handling code here:
        diemVan.setEnabled(false);
        diemSu.setEnabled(false);
        diemDia.setEnabled(false);
         diemToan.setEnabled(true);
        diemLy.setEnabled(true);
        diemHoa.setEnabled(true);
    }//GEN-LAST:event_khoiAActionPerformed

    private void khoiCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khoiCActionPerformed
        // TODO add your handling code here:
        diemToan.setEnabled(false);
        diemLy.setEnabled(false);
        diemHoa.setEnabled(false);
        diemVan.setEnabled(true);
        diemSu.setEnabled(true);
        diemDia.setEnabled(true);
    }//GEN-LAST:event_khoiCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField diemDia;
    private javax.swing.JTextField diemHoa;
    private javax.swing.JTextField diemLy;
    private javax.swing.JTextField diemSu;
    private javax.swing.JTextField diemToan;
    private javax.swing.JTextField diemVan;
    private javax.swing.JTextField hoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton khoiA;
    private javax.swing.JRadioButton khoiC;
    private javax.swing.JLabel lb_diaChi;
    private javax.swing.JLabel lb_diemDia;
    private javax.swing.JLabel lb_diemHoa;
    private javax.swing.JLabel lb_diemLy;
    private javax.swing.JLabel lb_diemSu;
    private javax.swing.JLabel lb_diemToan;
    private javax.swing.JLabel lb_diemVan;
    private javax.swing.JLabel lb_hoTen;
    private javax.swing.JLabel lb_khoi;
    private javax.swing.JLabel lb_ngaySinh;
    private javax.swing.JTextField ngaySinh;
    // End of variables declaration//GEN-END:variables
}
